### ISSUE TITLE
Select All feature in the Metabase Filtering System

### ISSUE THREAD

**Issue by TanTan412** [metabase/macaw#104]
If this question has been asked can I know if this is in the works or not? Cause I would like to have a Select all feature in the Metabase because my plan select all item and deselect the others if you know what I mean

**Comment by crisptrutski** [comment]
Hi @TanTan412 

Sorry I'm struggling to understand the question - could you give an example?

**Comment by TanTan412** [comment]
what I mean is to have a select all feature in the metabase in the filter

**Comment by crisptrutski** [comment]
This sounds like a feature request for Metabase itself, this library is only concerned with the analysis and rewriting on queries.
