### ISSUE TITLE
Add Malli schemas

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/macaw#24]
Bryan made [the cogent suggestion to add Malli schemas to function metadata as a means of documentation](https://github.com/metabase/macaw/pull/23#discussion_r1579844599) and [we've been planning for a while to Malli-fy everything](https://github.com/metabase/macaw/blob/73f706d0d59c2bc3a9c754609b61e16630208aa7/src/macaw/walk.clj#L9). All public functions and constants should have schemas.

**Comment by crisptrutski** [comment]
The schemas are starting to get quite wild, so we should consider doing this soon.
