### ISSUE TITLE
Square brace quotes (MSSQL) are not supported

### ISSUE THREAD

**Issue by crisptrutski** [metabase/macaw#42]
Currently Macaw is unable to correctly parse queries featuring squared bracket quoted identifiers, e.g.

```SQL
SELECT [my_field] FROM my_table
```

```clojure
(columns query)

;; Execution error (ParseException) at net.sf.jsqlparser.parser.CCJSqlParser/generateParseException (CCJSqlParser.java:39603).
;; Encountered unexpected token: "SELECT" <K_SELECT>
;;     at line 1, column 1.
;;
;; Was expecting one of:
;;
;;     "WITH"
```

The most obvious solution would be to update the JSQLParser grammar, but that would involve either a large upstream contribution, or forking the library, neither of which we are wanting to get into at this stage.

Since both Macaw and MSSQL can both support the use of double quotes for escaping, another solution could be to pre-process the query to make this substitution. Since double quotes require the `QUOTED_IDENTIFIER` setting to be enable though, it would be prudent to convert them back however when rewriting strings. Since the semantics of the two quoting methods are the same, and square braces do not require any settings, we could implicitly turn all quotes into square brackets as a post-processing step, regardless of whether the corresponding identifier was rewritten -  but we would prefer to preserve existing formatting as much as possible.

Since we can do this pre/post processing hack around our calls from Metabase to Macaw, we have no plans to fix this for now, although we might change our mind if there is 3rd party demand.

**Comment by tsmacdonald** [comment]
JSQLParser supports this, we just need to trigger it an an appropriate time (is "always" okay?)

https://jsqlparser.github.io/JSqlParser/usage.html#define-the-parser-features

**Comment by crisptrutski** [comment]
One way to support this is to take a new `:quote-character` argument in `opt`, which defaults to `'"`[^1][^2]. When `[` is present in that list we can enable the relevant option in JSQLParser. We only want to enable this for MSSQL, as it can mess with vector syntax in other dialects, so we'll also need a PR in Metabase to populate this option based on the driver.

IMHO we wouldn't don't need to worry about disabling any of the existing quotes if they're missing from the list, or supporting anything outside of `'"[`. We can simply `assert` that we're passed a subset.

[^2]: It seems like you can't escape back ticks in inline code snippets, so excuse the apostrophe in its place.
[^1]: We use a string as a convenient way to define a seq of characters.

**Comment by crisptrutski** [comment]
It's hard to determine the priority of this error, as we don't use MSSQL on Stats. Since the error message is not very definitive either, it's hard to create a metric for client instances too.
